config/routes.rb
Rails.application.routes.draw do
  resources :books do # everything after books added by me
    member do
      get :confirm_destroy
    end
  end

  # added by me
  root "books#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :price, presence: true, numericality:
    { greater_than_or_equal_to: 0 }
  validates :publish_date, presence: true
  # validate :must_be_valid_date

  # private

  # def must_be_valid_date
  #   return if publish_date.blank? # blank date
  #   Date.parse(publish_date.to_s)
  # rescue ArgumentError
  #   errors.add(:publish_date, "must be a valid date")
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json

  # for Book Collection 1
  def confirm_destroy
    @book = Book.find(params[:id])
  end
  # for Book Collection 1

  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_path, notice: "Book was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def book_params
      # params.expect(book: [ :title ])
      params.require(:book).permit(:title, :author, :price, :publish_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>
  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= number_with_precision(book.price, precision: 2) %>
  </p>
  <p>
    <strong>Published:</strong>
    <%= book.publish_date %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>
  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, step: 0.01 %>
  </div>
  <div>
    <%= form.label :publish_date, style: "display: block" %>
    <%= form.date_select :publish_date, start_year: 1900, end_year: Date.today.year %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/books/confirm_destroy.html.erb
<h1> WARNING </h1>
<h1> Are you sure you want to destroy "<%= @book.title %>"?</h1>
<%= button_to "Yes, destroy", @book, method: :delete %>
<%= link_to "Cancel and Go Back to Books", books_path %>

app/views/books/edit.html.erb
<% content_for :title, "Editing book" %>

<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Books" %>

<h1>Main Page</h1>

<h2>Book List</h2>
<em>Click on show to show book details!</em>
<p></p>
<div id="books">
  <% @books.each do |book| %>
    <!-- don't render whole book, just add title -->
    <strong><%= book.title %></strong> :::
      <%= link_to "Show", book %> ///
      <%= link_to "Edit", edit_book_path(book) %> /// 
      <%= link_to "Destroy", confirm_destroy_book_path(book), 
        style: "color: red;" %> 
    <br>
  <% end %>
</div>
<br>
<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<% content_for :title, "New book" %>

<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <p><%= link_to "Edit this book", edit_book_path(@book) %></p>
  <p>
    <%= link_to "Destroy this book", confirm_destroy_book_path(@book), 
    style: "color: red;"%>
  </p>
  <p><%= link_to "Back to books", books_path %></p>
  <!--
  <%= button_to "Destroy this book", @book, method: :delete %>
  -->
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Test App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>